apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    name: webservice
spec:
  selector:
    matchLabels:
      name: webservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: webservice
    spec:
      containers:
      - image: goserver
        name: webservice      
        imagePullPolicy: Always 
        ports:
        - containerPort:  8081
          name: webservice