apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    name: webservice
spec:
  selector:
    matchLabels:
      name: webservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: webservice
    spec:
      containers:
      - image: leonardomulticloud/gitops_webservice:5126209ab238fb19a4edff392f86ae569033b060
        name: webservice       
        ports:
        - containerPort:  8081
          name: webservice