apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops_webservice
  labels:
    name: gitops_webservice
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: gitops_webservice
    spec:
      containers:
      - image: goserver
        name: gitops_webservice       
        ports:
        - containerPort:  8080
          name: gitops_webservice