apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    name: webservice
spec:
  selector:
    matchLabels:
      name: webservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: webservice
    spec:
      containers:
      - image: goserver
        name: webservice      
        imagePullPolicy: Always 
        ports:
        - containerPort:  8081
          name: webservice
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 8081
        resources:
            limits:
              memory: 2000Mi
              cpu: 1000m
            requests:
              memory: 1000Mi
              cpu: 500m