apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
images:
- name: goserver
  newName: leonardomulticloud/gitops_webservice
  newTag: f6cbd1702220aaffba59c9773c21c54298d923ff
