apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
images:
- name: goserver
  newName: leonardomulticloud/gitops_webservice
  newTag: 03606f5d587fb3d31143040cd6404af2a6f0bb8e
